### ISSUE TITLE
Streamline document replace and delete capability

### ISSUE THREAD

**Issue by thephez** [dashevo/js-dash-sdk#144]
## Expected Behavior

Ability to update/delete documents without having to manually retrieve the document and extract `$id` and `$revision`.

## Current Behavior

It seems necessary to manually retrieve the document to be updated and then insert its id/revision when doing `client.platform.documents.create` as shown here:

```js
  // Retrieve existing document
  const documents = await client.platform.documents.get(
    'tutorialContract.note',
    {where: [['$id', '==', documentId]]}
  );

  // Create updated document
  const noteDocument = await platform.documents.create(
    'tutorialContract.note',
    identity,
    {
      '$id': documents[0].id, // Existing document id
      '$revision': documents[0].revision, // Existing document revision
      message: 'Updated document @ ' + new Date().toUTCString()
    },
  );
```

## Possible Solution

Addition of something like `client.platform.documents.replace` and `client.platform.documents.delete` which work like `client.platform.documents.create` but accept document ID as a parameter and use it to retrieve document and handle setting `$id` and `$revision` automatically.

**Comment by shumkov** [comment]
Actually, you don’t need to use `create` when you replace or delete it. Just get a document change what you need there `document.set(’name’, ’newName’)` and pass it to `broadcast(replace: [document])` or to `broadcast(delete:[document])` in case if you need to delete it.

**Comment by thephez** [comment]
Oh cool :+1: I wasn't familiar with document.set
