### ISSUE TITLE
evonet network is down

### ISSUE THREAD

**Issue by denniswong34** [dashevo/js-dash-sdk#197]
The evonet network is down.  Is there any other network that i could use for development??

## Expected Behavior
Evonet network connected without error

## Current Behavior
Error when creating wallet (1) : Failed to perform standard injections with reason: Plugin ChainPlugin of type Standard onStart failed: getaddrinfo ENOTFOUND seed-5.evonet.networks.dash.org

## Steps to Reproduce (for bugs)

1. client.getWalletAccount()

**Comment by shumkov** [comment]
Hello! We shout down evonet in favor of testnet in January.

**Comment by denniswong34** [comment]
How could i connect to the testnet?? May i know the seed address??

I could only find the evonet config from dapi-client. Could you send me the address for testnet??
@dashevo/dapi-client/lib/networkConfigs.js

module.exports = {
  evonet: {
    seeds: [
      'seed-1.evonet.networks.dash.org',
      'seed-2.evonet.networks.dash.org',
      'seed-3.evonet.networks.dash.org',
      'seed-4.evonet.networks.dash.org',
      'seed-5.evonet.networks.dash.org',
    ],
    network: 'evonet',
  },
  local: {
    dapiAddresses: ['127.0.0.1'],
    network: 'regtest',
  },
};

**Comment by thephez** [comment]
@denniswong34 The seeds are built in - you don't need to anything. The current version automatically connects to testnet. Please check out the tutorials here for some examples: https://dashplatform.readme.io/docs/tutorials-introduction
