### ISSUE TITLE
How could i connect to livenet or mainnet?

### ISSUE THREAD

**Issue by denniswong34** [dashevo/js-dash-sdk#200]
May i know how could i connect to dash main/live network?

**Comment by shumkov** [comment]
Hello. Dash Platform is not available on mainnet at the moment.

**Comment by thephez** [comment]
@denniswong34 You can join the community run developer Discord here: https://discord.gg/mU79ZWx. It's a good place to get answers to questions like you've been asking and interact with other developers.
