### ISSUE TITLE
v19: Error running platform.names.resolveByRecord() in browser

### ISSUE THREAD

**Issue by readme55** [dashevo/js-dash-sdk#221]
When i run this code in browser
```
console.log(await sdk.platform.names.resolveByRecord('dashUniqueIdentityId', '6KofS1fhpLU7RhekrvemTKRzLG48551xZm3PmSWZrH4o'))
```
i am getting 
```
{code: 3, message: "Invalid query: should be string", metadata: {…}}
```
When i run it in node on console it will return the correct username 'dappuser'.

It can be tested running Chrome Wallet and "importing an mnemonic" with existing username. This line will be executed and error comes up: https://github.com/readme55/Dash-Chrome-Wallet/blob/master/app/background.js#L398

**Comment by antouhou** [comment]
Hey! We've made one more bugfix release of the SDK - 3.19.4, can you please try it out?

**Comment by antouhou** [comment]
Report from the discord saying that 3.19.4 indeed fixed the issue.
