### ISSUE TITLE
webpack fails when bundling for web using webpack 5+

### ISSUE THREAD

**Issue by ICJR** [dashevo/js-dash-sdk#236]
Bundling for web using webpack 5 fails. Webpack 5+ doesn't provide polyfills for node packages by default.

## Expected Behavior

Successfully bundle browser JS dependent on this package

## Current Behavior

Bundling fails

## Possible Solution

- [pull request](https://github.com/dashevo/js-dash-sdk/pull/235)

## Context

- I was attempting to bundle a Platform dapp into a single file for IPFS upload/hosting

**Comment by dashameter** [comment]
@shumkov since the PR has been closed, can this issue be closed as well ?

**Comment by shumkov** [comment]
Yep, I think so.
